name: Selenium Test workflow

on: push

jobs:
  Selenium_Test_Job1:
    name: Selenium Test Job
    runs-on:  windows-latest

    steps:
      - run: echo "This is running inside a ${{ runner.os }} server in GitHub" 
      
